version: '3'

services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ../public:/home/www/:delegated
        container_name: nginx
    php:
        build:
            context: ./php
        volumes:
            - ../public:/home/www/:delegated
        container_name: php
    memcached:
        build: ./memcached
        container_name: memcache
        ports:
            - "11211:11211"
networks:
    app-network:
        driver: bridge