version: '3'

services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ../public:/home/www/:delegated
        extra_hosts:
            - "host.docker.internal:host-gateway"
        container_name: nginx
    php:
        build:
            context: ./php
        volumes:
            - ../public:/home/www/:delegated
        container_name: php
networks:
    app-network:
        driver: bridge