version: '3'

services:
    linux:
        build: ./linux
        image: linux
        volumes:
            - ../public:/root/
        stdin_open: true
        tty: true
networks:
    app-network:
        driver: bridge