version: '3'

services:
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ../public:/home/www/:delegated
    php:
        build:
            context: ./php
        image: php
        volumes:
            - ../public:/home/www/:delegated
    redis:
        build: ./redis
        image: redis
        ports: 
            - "6379:6379"
networks:
    app-network:
        driver: bridge