version: '3'

services:
    nginx:
        build: ./nginx
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ../public:/home/www/:delegated
        container_name: balancer
    nginx-primary:
        build: ./nginx
        volumes:
            - ../public:/home/www/:delegated
        container_name: nginx-primary
    nginx-secondry:
        build: ./nginx
        volumes:
            - ../public:/home/www/:delegated
        container_name: nginx-secondary
    php-primary:
        build:
            context: ./php
        volumes:
            - ../public:/home/www/:delegated
        container_name: php-primary
    php-secondary:
        build:
            context: ./php
        volumes:
            - ../public:/home/www/:delegated
        container_name: php-secondary
networks:
    app-network:
        driver: bridge